#!/bin/zsh
#
# One-time local setup so macOS stops re-asking for Accessibility permission on
# every rebuild.
#
# The problem: by default the app is ad-hoc signed, and an ad-hoc signature
# changes on every build. macOS keys the Accessibility grant to the signature,
# so each rebuild looks like a brand-new app and you get prompted again.
#
# The fix: sign every build with your stable Apple Development identity. This
# script detects that identity + your team, writes a gitignored
# Config/Local.xcconfig that the build picks up, regenerates the project, and
# clears any stale permission entries so you grant access exactly once.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

BUNDLE_ID="app.chime4breakfast"
LOCAL_XCCONFIG="Config/Local.xcconfig"

echo "Looking for an Apple Development signing identity..."
IDENTITY="$(
  security find-identity -v -p codesigning 2>/dev/null \
    | sed -n 's/.*"\(Apple Development: [^"]*\)".*/\1/p' \
    | head -n 1
)"

if [[ -z "$IDENTITY" ]]; then
  echo "No 'Apple Development' identity found in your keychain." >&2
  echo "Open Xcode > Settings > Accounts, add your Apple ID, and let it create" >&2
  echo "a development certificate, then run this script again." >&2
  exit 1
fi

# The team id is the 10-char code in the identity's certificate. Pull it from a
# throwaway signature of the identity so we do not have to parse the cert.
TEAM="$(
  security find-certificate -c "$IDENTITY" -p 2>/dev/null \
    | openssl x509 -noout -subject 2>/dev/null \
    | sed -n 's/.*OU *= *\([A-Z0-9]\{10\}\).*/\1/p' \
    | head -n 1
)"

echo "Found identity: $IDENTITY"
[[ -n "$TEAM" ]] && echo "Found team:     $TEAM"

mkdir -p Config
cat > "$LOCAL_XCCONFIG" <<EOF
// Generated by scripts/setup-signing.sh. Gitignored, per-machine.
// Signs every build with a stable identity so the Accessibility grant persists.
CODE_SIGN_STYLE = Manual
CODE_SIGN_IDENTITY = $IDENTITY
DEVELOPMENT_TEAM = $TEAM
EOF

echo "Wrote $LOCAL_XCCONFIG"

if command -v xcodegen >/dev/null 2>&1; then
  xcodegen generate >/dev/null
  echo "Regenerated Chime4Breakfast.xcodeproj"
fi

# Clear stale ad-hoc grants so the next launch registers the stable signature.
echo "Resetting the old Accessibility permission for $BUNDLE_ID..."
tccutil reset Accessibility "$BUNDLE_ID" >/dev/null 2>&1 || true

cat <<EOF

Done. From now on every build is signed with:
  $IDENTITY

Next: build and launch once (./scripts/run-debug.sh), grant Accessibility when
prompted, and it will stick across future rebuilds.
EOF
